# Generated by Django 2.1.2 on 2018-12-19 11:49
import json
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.multilingual.database


def merge_machine_usage_rule_fields(apps, schema_editor):
    MachineUsageRule = apps.get_model("make_queue", "machineusagerule")
    for rule in MachineUsageRule.objects.all():
        rule.content = json.dumps({
            "nb": rule.content,
            "en": rule.content_en,
        })
        rule.save()


def reverse_merge_machine_usage_rule_fields(apps, schema_editor):
    MachineUsageRule = apps.get_model("make_queue", "machineusagerule")
    for rule in MachineUsageRule.objects.all():
        content_dict = json.loads(rule.content)
        rule.content = content_dict["nb"]
        rule.content_en = content_dict["en"]
        rule.save()


class Migration(migrations.Migration):
    dependencies = [
        ('make_queue', '0008_auto_20181103_1524'),
    ]

    operations = [
        migrations.RunPython(merge_machine_usage_rule_fields, reverse_merge_machine_usage_rule_fields),
        migrations.RemoveField(
            model_name='machineusagerule',
            name='content_en',
        ),
        migrations.AlterField(
            model_name='machineusagerule',
            name='content',
            field=web.multilingual.database.MultiLingualRichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='news.TimePlace', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_queue.Machine',
                                    verbose_name='Machine'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='make_queue.Quota',
                                    verbose_name='Quota'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='showed',
            field=models.NullBooleanField(default=None, verbose_name='Showed'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special',
            field=models.BooleanField(default=False, verbose_name='MAKE NTNU'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='User'),
        ),
    ]
